'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'es' | 'nl' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  es: {
    // Navegación
    'nav.home': 'Inicio',
    'nav.measurement': 'Medición',
    'nav.marking': 'Marcado',
    'nav.fields': 'Campos',
    'nav.history': 'Historial',
    'nav.export': 'Exportar',
    'nav.map': 'Mapa',
    'nav.calendar': 'Calendario',
    'nav.products': 'Productos',
    
    // Home
    'home.title': 'Lissewege Fields - R.F.C. Lissewege',
    'home.subtitle': 'Sistema inteligente para medición y marcado de campos',
    'home.measurement': 'Medición',
    'home.measurement.desc': 'Medir dimensiones del campo',
    'home.marking': 'Marcado',
    'home.marking.desc': 'Marcar líneas del campo',
    'home.fields': 'Campos',
    'home.fields.desc': 'Gestionar campos deportivos',
    'home.history': 'Historial',
    'home.history.desc': 'Ver mediciones anteriores',
    'home.features': 'Características',
    'home.camera': 'Cámara integrada para medición',
    'home.gps': 'GPS de alta precisión',
    'home.fifa': 'Estándares FIFA',
    'home.multiple': 'Múltiples campos',
    
    // Herramientas de cámara
    'camera.tools': 'Herramientas de Cámara',
    'camera.tracking': 'Punto de Seguimiento',
    'camera.tracking.desc': 'Punto central para seguir al caminar',
    'camera.guidelines': 'Líneas Guía',
    'camera.guidelines.desc': 'Líneas paralelas para mantener rectitud',
    'camera.measurement': 'Metraje en Vivo',
    'camera.measurement.desc': 'Medición en tiempo real en pantalla',
    'camera.tracker': 'Rastreador de Ruta',
    'camera.tracker.desc': 'Visualizar camino recorrido',
    'camera.straightness': 'Verificador de Rectitud',
    'camera.straightness.desc': 'Analizar si la línea está derecha',
    'camera.width': 'Ancho líneas guía',
    'camera.distance': 'Distancia recorrida',
    'camera.rectitude': 'Rectitud',
    
    // Medición
    'measurement.title': 'Medición Móvil',
    'measurement.start': 'Iniciar Medición',
    'measurement.stop': 'Detener Medición',
    'measurement.camera.start': 'Activar Cámara',
    'measurement.camera.stop': 'Desactivar Cámara',
    'measurement.gps.start': 'Activar GPS',
    'measurement.gps.stop': 'Desactivar GPS',
    'measurement.capture': 'Capturar Punto',
    'measurement.clear': 'Limpiar',
    'measurement.points': 'puntos',
    'measurement.distance.estimated': 'Distancia estimada',
    'measurement.advanced': 'Modo Avanzado',
    'measurement.tap.capture': 'Toca para capturar',
    'measurement.tap.start': 'Toca "Iniciar" para comenzar la medición',
    'measurement.camera.inactive': 'Cámara no activa',
    'measurement.camera.activating': 'Activando cámara...',
    'measurement.camera.active': 'Cámara activa. Toca la pantalla para capturar puntos.',
    'measurement.camera.error': 'No se pudo acceder a la cámara. Verifica los permisos.',
    'measurement.camera.error.init': 'Error al iniciar cámara.',
    'measurement.camera.stopped': 'Cámara detenida.',
    'measurement.gps.getting': 'Obteniendo posición GPS...',
    'measurement.stopped': 'Medición detenida. Se necesitan al menos 2 puntos.',
    'measurement.reset': 'Medición reiniciada.',
    'measurement.web.penalty.north': 'Área de Penal Norte',
    'measurement.web.penalty.south': 'Área de Penal Sur',
    'measurement.web.center.circle': 'Círculo Central',
    'measurement.web.type.line': 'Línea',
    'measurement.web.camera.starting': 'Iniciando cámara para medición...',
    'measurement.web.camera.ready': 'Cámara activa. Toca la pantalla para capturar puntos de medición.',
    'measurement.web.camera.error': 'No se pudo acceder a la cámara. Verifica los permisos.',
    'measurement.web.gps.connecting': 'Conectando al GPS de alta precisión para medición FIFA...',
    'measurement.web.gps.active': 'GPS de alta precisión activo. Listo para medición profesional FIFA.',
    'measurement.web.gps.error': 'Error al obtener posición GPS. Verifica los permisos de ubicación.',
    'measurement.web.fifa.start': 'Medición profesional FIFA iniciada. Sistema GPS de alta precisión activo.',
    'measurement.web.fifa.stopped': 'Medición detenida. Calculando resultados FIFA...',
    'measurement.web.tracking.active': 'Modo seguimiento activo. La cámara detectará automáticamente líneas.',
    'measurement.web.mode.basic': 'Modo Básico',
    'measurement.web.mode.advanced': 'Modo Avanzado',
    'measurement.web.activate.gps': 'Activar GPS',
    'measurement.web.start.pro': 'Iniciar Medición Pro',
    'measurement.web.activate.camera': 'Activar Cámara',
    'measurement.web.stop.camera': 'Detener Cámara',
    'measurement.length.total': 'Longitud Total',
    'measurement.width.total': 'Ancho Total',
    'measurement.distance.walked': 'Distancia Recorrida',
    'measurement.recording': 'Grabando...',
    'measurement.ready': 'Listo',
    
    // Modo Avanzado
    'advanced.mode.on': 'Modo Avanzado ON',
    'advanced.mode.off': 'Modo Básico',
    'advanced.configuration': 'Configuración Avanzada',
    'advanced.features.enabled': 'Características Activas',
    'advanced.more': 'más',
    'advanced.camera.ai': 'IA de Cámara',
    'advanced.camera.ai.desc': 'Detección inteligente con visión artificial',
    'advanced.line.detection': 'Detección de Líneas',
    'advanced.line.detection.desc': 'Reconocimiento automático de líneas del campo',
    'advanced.precision.tracking': 'Tracking de Precisión',
    'advanced.precision.tracking.desc': 'Seguimiento GPS submétrico profesional',
    'advanced.analytics.realtime': 'Analytics en Tiempo Real',
    'advanced.analytics.realtime.desc': 'Métricas y estadísticas instantáneas',
    'advanced.camera.tools': 'Herramientas de Cámara',
    'advanced.camera.tools.desc': 'Overlay inteligente y guías de medición',
    'advanced.gps.professional': 'GPS Profesional',
    'advanced.gps.professional.desc': 'Configuración avanzada de posicionamiento',
    'advanced.category.camera': 'Cámara',
    'advanced.category.gps': 'GPS',
    'advanced.category.ai': 'Inteligencia Artificial',
    'advanced.category.analytics': 'Analytics',
    
    // IA y Detección
    'ai.detection.active': 'IA Activa',
    'ai.confidence': 'Confianza',
    'ai.lines.detected': 'Líneas',
    'ai.legend': 'Leyenda',
    'ai.boundary.lines': 'Líneas Límite',
    'ai.goal.lines': 'Líneas de Portería',
    'ai.penalty.lines': 'Área Penal',
    'ai.center.line': 'Línea Central',
    
    // Plantillas FIFA
    'fifa.template.11v11': 'FIFA 11v11 Profesional',
    'fifa.template.11v11.desc': 'Campo oficial FIFA para competiciones profesionales',
    'fifa.template.7v7': 'FIFA 7v7 Juvenil',
    'fifa.template.7v7.desc': 'Campo reducido para desarrollo juvenil',
    'fifa.template.futsal': 'FIFA Futsal',
    'fifa.template.futsal.desc': 'Campo de futsal oficial para juego indoor',
    'fifa.template.training': 'Campo de Entrenamiento',
    'fifa.template.training.desc': 'Campo flexible para práctica y entrenamiento',
    'fifa.category.professional': 'Profesional',
    'fifa.category.youth': 'Juvenil',
    'fifa.category.futsal': 'Futsal',
    'fifa.category.training': 'Entrenamiento',
    'fifa.feature.official': 'Oficial FIFA',
    'fifa.feature.professional': 'Profesional',
    'fifa.feature.worldcup': 'Mundial',
    'fifa.feature.uefa': 'UEFA',
    'fifa.feature.youth': 'Juvenil',
    'fifa.feature.development': 'Desarrollo',
    'fifa.feature.schools': 'Escuelas',
    'fifa.feature.grassroots': 'Base',
    'fifa.feature.indoor': 'Indoor',
    'fifa.feature.smallsided': 'Reducido',
    'fifa.feature.technique': 'Técnica',
    'fifa.feature.fast': 'Rápido',
    'fifa.feature.training': 'Entrenamiento',
    'fifa.feature.practice': 'Práctica',
    'fifa.feature.flexible': 'Flexible',
    'fifa.feature.multipurpose': 'Multiuso',
    'fifa.length': 'Longitud',
    'fifa.width': 'Ancho',
    'fifa.official': 'Oficial',
    'fifa.templates.title': 'Plantillas FIFA',
    'fifa.templates.subtitle': 'Selecciona un estándar FIFA oficial',
    'fifa.search.placeholder': 'Buscar plantillas...',
    'fifa.no.results': 'No se encontraron plantillas',
    'fifa.clear.filters': 'Limpiar filtros',
    'fifa.templates.found': 'plantillas encontradas',
    'fifa.cancel': 'Cancelar',
    'fifa.apply.template': 'Aplicar Plantilla',
    
    // Sistema de Exportación
    'export.title': 'Sistema de Exportación Avanzado',
    'export.subtitle': 'Generar reportes profesionales para',
    'export.select.format': 'Seleccionar Formato',
    'export.settings': 'Configuración',
    'export.fifa.certificate': 'Certificado FIFA',
    'export.fifa.certificate.desc': 'Certificado oficial FIFA con firma digital',
    'export.technical.report': 'Reporte Técnico',
    'export.technical.report.desc': 'Análisis detallado con recomendaciones',
    'export.csv.data': 'Datos CSV',
    'export.csv.data.desc': 'Datos estructurados para análisis',
    'export.json.api': 'JSON API',
    'export.json.api.desc': 'Datos estructurados para integración',
    'export.field.map': 'Mapa del Campo',
    'export.field.map.desc': 'Representación visual de alta resolución',
    'export.photo.gallery': 'Galería de Fotos',
    'export.photo.gallery.desc': 'Todas las fotos organizadas con metadatos',
    'export.feature.official': 'Oficial FIFA',
    'export.feature.fifa.logo': 'Logo FIFA',
    'export.feature.digital.signature': 'Firma Digital',
    'export.feature.compliance': 'Cumplimiento',
    'export.feature.detailed': 'Detallado',
    'export.feature.measurements': 'Mediciones',
    'export.feature.analysis': 'Análisis',
    'export.feature.recommendations': 'Recomendaciones',
    'export.feature.raw.data': 'Datos Brutos',
    'export.feature.excel.compatible': 'Compatible Excel',
    'export.feature.analysis.ready': 'Listo Análisis',
    'export.feature.lightweight': 'Ligero',
    'export.feature.structured': 'Estructurado',
    'export.feature.api.ready': 'API Ready',
    'export.feature.integration': 'Integración',
    'export.feature.developer': 'Desarrollador',
    'export.feature.visual': 'Visual',
    'export.feature.high.resolution': 'Alta Resolución',
    'export.feature.overlays': 'Overlays',
    'export.feature.printable': 'Imprimible',
    'export.feature.all.photos': 'Todas las Fotos',
    'export.feature.organized': 'Organizadas',
    'export.feature.metadata': 'Metadatos',
    'export.feature.timestamp': 'Timestamp',
    'export.premium': 'Premium',
    'export.selected': 'Seleccionado',
    'export.include.photos': 'Incluir Fotos',
    'export.include.gps': 'Incluir GPS',
    'export.quality': 'Calidad',
    'export.quality.low': 'Baja',
    'export.quality.medium': 'Media',
    'export.quality.high': 'Alta',
    'export.language': 'Idioma',
    'export.data.preview': 'Vista Previa',
    'export.measurements': 'Mediciones',
    'export.markings': 'Marcados',
    'export.photos': 'Fotos',
    'export.gps.points': 'Puntos GPS',
    'export.cancel': 'Cancelar',
    'export.download': 'Descargar',
    'export.processing': 'Procesando...',
    'export.step.preparing': 'Preparando datos...',
    'export.step.processing': 'Procesando información...',
    'export.step.generating': 'Generando archivo...',
    'export.step.finalizing': 'Finalizando...',
    'export.step.complete': 'Completo',
    'export.error': 'Error en exportación',
    
    // Analytics Dashboard
    'analytics.dashboard': 'Dashboard de Analytics',
    'analytics.subtitle': 'Análisis avanzado de rendimiento',
    'analytics.7days': '7 días',
    'analytics.30days': '30 días', 
    'analytics.90days': '90 días',
    'analytics.1year': '1 año',
    'analytics.export': 'Exportar',
    'analytics.total.measurements': 'Total Mediciones',
    'analytics.this.week': 'esta semana',
    'analytics.avg.accuracy': 'Precisión Promedio',
    'analytics.measurement.accuracy': 'Precisión de medición',
    'analytics.total.markings': 'Total Marcados',
    'analytics.completed': 'completados',
    'analytics.avg.duration': 'Duración Promedio',
    'analytics.per.session': 'por sesión',
    'analytics.performance.metrics': 'Métricas de Rendimiento',
    'analytics.gps.accuracy': 'Precisión GPS',
    'analytics.speed.avg': 'Velocidad Promedio',
    'analytics.error.rate': 'Tasa de Error',
    'analytics.efficiency': 'Eficiencia',
    'analytics.fifa.compliance': 'Cumplimiento FIFA',
    'analytics.compliant': 'cumple',
    'analytics.local': 'Local',
    'analytics.overall': 'General',
    'analytics.excellent': 'Excelente',
    'analytics.usage.statistics': 'Estadísticas de Uso',
    'analytics.total.time': 'Tiempo Total',
    'analytics.avg.session': 'Sesión Promedio',
    'analytics.peak.hour': 'Hora Pico',
    'analytics.active.users': 'Usuarios Activos',
    'analytics.insights': 'Insights y Recomendaciones',
    'analytics.positive.trend': 'Tendencia Positiva',
    'analytics.recommendation': 'Recomendación',
    'analytics.insight.accuracy.improving': 'La precisión de medición está mejorando consistentemente.',
    'analytics.recommendation.calibration': 'Considera calibrar el GPS para mejor precisión.',
    
    // Sistema de Gamificación
    'gamification.level': 'Nivel',
    'gamification.points': 'Puntos',
    'gamification.achievements': 'Logros',
    'gamification.next.level': 'Siguiente Nivel',
    'gamification.points.remaining': 'puntos restantes',
    'gamification.measurements': 'Mediciones',
    'gamification.markings': 'Marcados',
    'gamification.accuracy': 'Precisión',
    'gamification.streak': 'Racha',
    'gamification.unlocked': 'desbloqueados',
    'gamification.progress': 'Progreso',
    'gamification.unlocked.on': 'Desbloqueado el',
    
    // Logros
    'achievement.unlocked': 'Logro Desbloqueado',
    'achievement.points': 'puntos',
    'achievement.category.all': 'Todos',
    'achievement.category.measurement': 'Medición',
    'achievement.category.marking': 'Marcado',
    'achievement.category.accuracy': 'Precisión',
    'achievement.category.speed': 'Velocidad',
    'achievement.category.consistency': 'Consistencia',
    
    'achievement.first.measurement': 'Primera Medición',
    'achievement.first.measurement.desc': 'Completa tu primera medición',
    'achievement.precision.master': 'Maestro de Precisión',
    'achievement.precision.master.desc': 'Alcanza 95% de precisión',
    'achievement.speed.demon': 'Demonio de la Velocidad',
    'achievement.speed.demon.desc': 'Completa 10 mediciones rápidamente',
    'achievement.marathon.walker': 'Caminante Maratón',
    'achievement.marathon.walker.desc': 'Camina una distancia de maratón',
    'achievement.consistency.king': 'Rey de la Consistencia',
    'achievement.consistency.king.desc': 'Mantén una racha de 30 días',
    'achievement.field.master': 'Maestro del Campo',
    'achievement.field.master.desc': 'Completa 100 campos',
    
    'achievement.req.complete.measurement': 'Completar una medición',
    'achievement.req.accuracy.95': 'Alcanzar 95% de precisión',
    'achievement.req.ten.measurements': 'Completar 10 mediciones',
    'achievement.req.walk.marathon': 'Caminar 42.195 km',
    'achievement.req.thirty.days': 'Racha de 30 días',
    'achievement.req.hundred.fields': 'Completar 100 campos',
    
    // Calendario
    'calendar.title': 'Calendario de Eventos',
    'calendar.no.events': 'No hay eventos programados',
    'calendar.add.event': 'Agregar Evento',
    'calendar.today': 'Hoy',
    'calendar.month': 'Mes',
    'calendar.week': 'Semana',
    'calendar.day': 'Día',
    'calendar.event.maintenance': 'Mantenimiento de Campo',
    'calendar.event.match': 'Partido',
    'calendar.event.training': 'Entrenamiento',
    'calendar.event.inspection': 'Inspección',
    'calendar.event.tournament': 'Torneo',
    'calendar.event.meeting': 'Reunión',
    'calendar.event.details': 'Detalles del Evento',
    'calendar.event.start': 'Inicio',
    'calendar.event.end': 'Fin',
    'calendar.event.location': 'Ubicación',
    'calendar.event.description': 'Descripción',
    'calendar.event.participants': 'Participantes',
    'calendar.event.status': 'Estado',
    'calendar.event.confirmed': 'Confirmado',
    'calendar.event.pending': 'Pendiente',
    'calendar.event.cancelled': 'Cancelado',
    'calendar.filter.all': 'Todos los Eventos',
    'calendar.filter.maintenance': 'Mantenimiento',
    'calendar.filter.matches': 'Partidos',
    'calendar.filter.training': 'Entrenamientos',
    'calendar.upcoming': 'Próximos Eventos',
    'calendar.past': 'Eventos Pasados',
    'calendar.reminder': 'Recordatorio',
    'calendar.notification': 'Notificación',
    'calendar.sync': 'Sincronizar',
    'calendar.export': 'Exportar Calendario',
    'calendar.import': 'Importar Eventos',
    
    // Productos
    'products.title': 'Gestión de Productos Pro',
    'products.subtitle': 'Sistema profesional de inventario y gestión de productos FIFA',
    'products.category.equipment': 'Equipamiento',
    'products.category.maintenance': 'Mantenimiento',
    'products.category.marking': 'Marcado',
    'products.category.measurement': 'Medición',
    'products.category.certification': 'Certificación',
    'products.featured': 'Productos Destacados',
    'products.new': 'Nuevos Productos',
    'products.bestseller': 'Más Vendidos',
    'products.on.sale': 'En Oferta',
    'products.price': 'Precio',
    'products.availability': 'Disponibilidad',
    'products.in.stock': 'En Stock',
    'products.out.of.stock': 'Sin Stock',
    'products.limited.stock': 'Stock Limitado',
    'products.add.to.cart': 'Agregar al Carrito',
    'products.buy.now': 'Comprar Ahora',
    'products.view.details': 'Ver Detalles',
    'products.specifications': 'Especificaciones',
    'products.reviews': 'Reseñas',
    'products.rating': 'Calificación',
    'products.warranty': 'Garantía',
    'products.shipping': 'Envío',
    'products.delivery': 'Entrega',
    'products.compare': 'Comparar',
    'products.wishlist': 'Lista de Deseos',
    'products.share': 'Compartir',
    'products.similar': 'Productos Similares',
    'products.accessories': 'Accesorios',
    'products.bundle': 'Paquete',
    'products.discount': 'Descuento',
    'products.fifa.certified': 'Certificado FIFA',
    'products.uefa.approved': 'Aprobado UEFA',
    'products.professional.grade': 'Grado Profesional',
    'products.search.placeholder': 'Buscar productos...',
    'products.filter.price': 'Filtrar por Precio',
    'products.filter.brand': 'Filtrar por Marca',
    'products.filter.rating': 'Filtrar por Calificación',
    'products.sort.name': 'Ordenar por Nombre',
    'products.sort.price.asc': 'Precio: Menor a Mayor',
    'products.sort.price.desc': 'Precio: Mayor a Menor',
    'products.sort.rating': 'Ordenar por Calificación',
    'products.sort.newest': 'Más Nuevos',
    'products.results': 'resultados encontrados',
    'products.no.results': 'No se encontraron productos',
    'products.clear.filters': 'Limpiar Filtros',
    'products.items': 'Productos',
    'products.low.stock': 'Bajo Stock',
    'products.fifa.standards': 'Estándares FIFA',
    'products.inventory.status': 'Estado del Inventario',
    
    // Marcado
    'marking.title': 'Marcado Móvil',
    'marking.line.center': 'Línea Central',
    'marking.line.penalty': 'Área Penal',
    'marking.line.corner': 'Círculo Esquina',
    'marking.line.goal': 'Área de Meta',
    'marking.progress': 'Progreso',
    'marking.complete': 'Completar Línea',
    'marking.reset': 'Reiniciar Marcado',
    'marking.line.goal.north': 'Línea de Meta Norte',
    'marking.line.goal.south': 'Línea de Meta Sur',
    'marking.line.side.left': 'Línea Lateral Izquierda',
    'marking.line.side.right': 'Línea Lateral Derecha',
    'marking.circle.center': 'Círculo Central',
    'marking.camera.activating': 'Activando cámara...',
    'marking.camera.active': 'Cámara activa. Toca la pantalla para marcar puntos.',
    'marking.camera.error': 'No se pudo acceder a la cámara. Verifica los permisos.',
    'marking.camera.error.init': 'Error al iniciar cámara.',
    'marking.camera.stopped': 'Cámara detenida.',
    'marking.gps.getting': 'Obteniendo posición GPS...',
    'marking.gps.active': 'GPS activo. Mueve el dispositivo para marcar líneas.',
    
    // Configuración
    'settings.language': 'Idioma',
    'settings.spanish': 'Español',
    'settings.dutch': 'Holandés',
    'settings.english': 'Inglés',
    
    // Estados
    'status.online': 'En línea',
    'status.offline': 'Sin conexión',
    'status.connecting': 'Conectando...',
    'status.active': 'Activo',
    'status.inactive': 'Inactivo',
    'status.measuring': 'Midiendo...',
    'status.marking': 'Marcando...',
    'status.gps': 'GPS Activo',
    
    // Botones generales
    'btn.start': 'Iniciar',
    'btn.stop': 'Detener',
    'btn.continue': 'Continuar',
    'btn.complete': 'Completar',
    'btn.cancel': 'Cancelar',
    'btn.save': 'Guardar',
    'btn.clear': 'Limpiar',
    'btn.reset': 'Reiniciar'
  },
  
  nl: {
    // Navigatie
    'nav.home': 'Home',
    'nav.measurement': 'Meting',
    'nav.marking': 'Markering',
    'nav.fields': 'Velden',
    'nav.history': 'Geschiedenis',
    'nav.export': 'Exporteren',
    'nav.map': 'Kaart',
    'nav.calendar': 'Kalender',
    'nav.products': 'Producten',
    
    // Home
    'home.title': 'Lissewege Fields - R.F.C. Lissewege',
    'home.subtitle': 'Intelligent systeem voor veldmeting en -markering',
    'home.measurement': 'Meting',
    'home.measurement.desc': 'Veldafmetingen meten',
    'home.marking': 'Markering',
    'home.marking.desc': 'Veldlijnen markeren',
    'home.fields': 'Velden',
    'home.fields.desc': 'Sportvelden beheren',
    'home.history': 'Geschiedenis',
    'home.history.desc': 'Vorige metingen bekijken',
    'home.features': 'Kenmerken',
    'home.camera': 'Geïntegreerde camera voor meting',
    'home.gps': 'Hoge precisie GPS',
    'home.fifa': 'FIFA-standaarden',
    'home.multiple': 'Meerdere velden',
    
    // Camera tools
    'camera.tools': 'Camera Gereedschappen',
    'camera.tracking': 'Volgpunt',
    'camera.tracking.desc': 'Centraal punt om te volgen tijdens het lopen',
    'camera.guidelines': 'Gidslijnen',
    'camera.guidelines.desc': 'Parallelle lijnen voor rechtheid',
    'camera.measurement': 'Live Meting',
    'camera.measurement.desc': 'Real-time meting op scherm',
    'camera.tracker': 'Route Tracker',
    'camera.tracker.desc': 'Gelopen pad visualiseren',
    'camera.straightness': 'Rechtheid Checker',
    'camera.straightness.desc': 'Analyseren of lijn recht is',
    'camera.width': 'Breedte gidslijnen',
    'camera.distance': 'Afgelegde afstand',
    'camera.rectitude': 'Rechtheid',
    
    // Meting
    'measurement.title': 'Mobiele Meting',
    'measurement.start': 'Meting Starten',
    'measurement.stop': 'Meting Stoppen',
    'measurement.camera.start': 'Camera Activeren',
    'measurement.camera.stop': 'Camera Deactiveren',
    'measurement.gps.start': 'GPS Activeren',
    'measurement.gps.stop': 'GPS Deactiveren',
    'measurement.capture': 'Punt Vastleggen',
    'measurement.clear': 'Wissen',
    'measurement.points': 'punten',
    'measurement.distance.estimated': 'Geschatte afstand',
    'measurement.advanced': 'Geavanceerde Modus',
    'measurement.tap.capture': 'Tik om vast te leggen',
    'measurement.tap.start': 'Tik "Starten" om meting te beginnen',
    'measurement.camera.inactive': 'Camera niet actief',
    'measurement.camera.activating': 'Camera activeren...',
    'measurement.camera.active': 'Camera actief. Tik op scherm om punten vast te leggen.',
    'measurement.camera.error': 'Geen toegang tot camera. Controleer toestemmingen.',
    'measurement.camera.error.init': 'Fout bij opstarten camera.',
    'measurement.camera.stopped': 'Camera gestopt.',
    'measurement.gps.getting': 'GPS-positie ophalen...',
    'measurement.stopped': 'Meting gestopt. Minimaal 2 punten nodig.',
    'measurement.reset': 'Meting herstart.',
    'measurement.web.penalty.north': 'Strafschopgebied Noord',
    'measurement.web.penalty.south': 'Strafschopgebied Zuid',
    'measurement.web.center.circle': 'Middencirkel',
    'measurement.web.type.line': 'Lijn',
    'measurement.web.camera.starting': 'Camera starten voor meting...',
    'measurement.web.camera.ready': 'Camera actief. Tik op scherm om meetpunten vast te leggen.',
    'measurement.web.camera.error': 'Geen toegang tot camera. Controleer toestemmingen.',
    'measurement.web.gps.connecting': 'Verbinding maken met hoge precisie GPS voor FIFA meting...',
    'measurement.web.gps.active': 'Hoge precisie GPS actief. Klaar voor professionele FIFA meting.',
    'measurement.web.gps.error': 'Fout bij ophalen GPS-positie. Controleer locatietoestemmingen.',
    'measurement.web.fifa.start': 'Professionele FIFA meting gestart. Hoge precisie GPS-systeem actief.',
    'measurement.web.fifa.stopped': 'Meting gestopt. FIFA resultaten berekenen...',
    'measurement.web.tracking.active': 'Volg modus actief. Camera detecteert automatisch lijnen.',
    'measurement.web.mode.basic': 'Basis Modus',
    'measurement.web.mode.advanced': 'Geavanceerde Modus',
    'measurement.web.activate.gps': 'GPS Activeren',
    'measurement.web.start.pro': 'Start Pro Meting',
    'measurement.web.activate.camera': 'Camera Activeren',
    'measurement.web.stop.camera': 'Camera Stoppen',
    'measurement.length.total': 'Totale Lengte',
    'measurement.width.total': 'Totale Breedte',
    'measurement.distance.walked': 'Gelopen Afstand',
    'measurement.recording': 'Opnemen...',
    'measurement.ready': 'Klaar',
    
    // Geavanceerde Modus
    'advanced.mode.on': 'Geavanceerde Modus AAN',
    'advanced.mode.off': 'Basis Modus',
    'advanced.configuration': 'Geavanceerde Configuratie',
    'advanced.features.enabled': 'Actieve Functies',
    'advanced.more': 'meer',
    'advanced.camera.ai': 'Camera AI',
    'advanced.camera.ai.desc': 'Intelligente detectie met computer vision',
    'advanced.line.detection': 'Lijndetectie',
    'advanced.line.detection.desc': 'Automatische herkenning van veldlijnen',
    'advanced.precision.tracking': 'Precisie Tracking',
    'advanced.precision.tracking.desc': 'Professionele submetrische GPS-tracking',
    'advanced.analytics.realtime': 'Real-time Analytics',
    'advanced.analytics.realtime.desc': 'Directe metrics en statistieken',
    'advanced.camera.tools': 'Camera Tools',
    'advanced.camera.tools.desc': 'Intelligente overlay en meetgidsen',
    'advanced.gps.professional': 'Professionele GPS',
    'advanced.gps.professional.desc': 'Geavanceerde positioneringsconfiguratie',
    'advanced.category.camera': 'Camera',
    'advanced.category.gps': 'GPS',
    'advanced.category.ai': 'Kunstmatige Intelligentie',
    'advanced.category.analytics': 'Analytics',
    
    // AI en Detectie
    'ai.detection.active': 'AI Actief',
    'ai.confidence': 'Betrouwbaarheid',
    'ai.lines.detected': 'Lijnen',
    'ai.legend': 'Legenda',
    'ai.boundary.lines': 'Grenslijnen',
    'ai.goal.lines': 'Doellijnen',
    'ai.penalty.lines': 'Strafschopgebied',
    'ai.center.line': 'Middenlijn',
    
    // Markering
    'marking.title': 'Mobiele Markering',
    'marking.line.center': 'Middenlijn',
    'marking.line.penalty': 'Strafschopgebied',
    'marking.line.corner': 'Hoekschop Cirkel',
    'marking.line.goal': 'Doelgebied',
    'marking.progress': 'Voortgang',
    'marking.complete': 'Lijn Voltooien',
    'marking.reset': 'Markering Herstellen',
    'marking.line.goal.north': 'Doellijn Noord',
    'marking.line.goal.south': 'Doellijn Zuid',
    'marking.line.side.left': 'Zijlijn Links',
    'marking.line.side.right': 'Zijlijn Rechts',
    'marking.circle.center': 'Middencirkel',
    'marking.camera.activating': 'Camera activeren...',
    'marking.camera.active': 'Camera actief. Tik op scherm om punten te markeren.',
    'marking.camera.error': 'Geen toegang tot camera. Controleer toestemmingen.',
    'marking.camera.error.init': 'Fout bij opstarten camera.',
    'marking.camera.stopped': 'Camera gestopt.',
    'marking.gps.getting': 'GPS-positie ophalen...',
    'marking.gps.active': 'GPS actief. Beweeg apparaat om lijnen te markeren.',
    
    // Instellingen
    'settings.language': 'Taal',
    'settings.spanish': 'Spaans',
    'settings.dutch': 'Nederlands',
    'settings.english': 'Engels',
    
    // Status
    'status.online': 'Online',
    'status.offline': 'Offline',
    'status.connecting': 'Verbinden...',
    'status.active': 'Actief',
    'status.inactive': 'Inactief',
    'status.measuring': 'Aan het meten...',
    'status.marking': 'Aan het markeren...',
    'status.gps': 'GPS Actief',
    
    // Algemene knoppen
    'btn.start': 'Starten',
    'btn.stop': 'Stoppen',
    'btn.continue': 'Doorgaan',
    'btn.complete': 'Voltooien',
    'btn.cancel': 'Annuleren',
    'btn.save': 'Opslaan',
    'btn.clear': 'Wissen',
    'btn.reset': 'Herstellen',
    
    // Kalender
    'calendar.title': 'Evenementenkalender',
    'calendar.no.events': 'Geen evenementen gepland',
    'calendar.add.event': 'Evenement Toevoegen',
    'calendar.today': 'Vandaag',
    'calendar.month': 'Maand',
    'calendar.week': 'Week',
    'calendar.day': 'Dag',
    'calendar.event.maintenance': 'Veldonderhoud',
    'calendar.event.match': 'Wedstrijd',
    'calendar.event.training': 'Training',
    'calendar.event.inspection': 'Inspectie',
    'calendar.event.tournament': 'Toernooi',
    'calendar.event.meeting': 'Vergadering',
    'calendar.event.details': 'Evenementdetails',
    'calendar.event.start': 'Start',
    'calendar.event.end': 'Einde',
    'calendar.event.location': 'Locatie',
    'calendar.event.description': 'Beschrijving',
    'calendar.event.participants': 'Deelnemers',
    'calendar.event.status': 'Status',
    'calendar.event.confirmed': 'Bevestigd',
    'calendar.event.pending': 'In Afwachting',
    'calendar.event.cancelled': 'Geannuleerd',
    'calendar.filter.all': 'Alle Evenementen',
    'calendar.filter.maintenance': 'Onderhoud',
    'calendar.filter.matches': 'Wedstrijden',
    'calendar.filter.training': 'Trainingen',
    'calendar.upcoming': 'Komende Evenementen',
    'calendar.past': 'Eerdere Evenementen',
    'calendar.reminder': 'Herinnering',
    'calendar.notification': 'Melding',
    'calendar.sync': 'Synchroniseren',
    'calendar.export': 'Kalender Exporteren',
    'calendar.import': 'Evenementen Importeren',
    
    // Producten
    'products.title': 'Productbeheer Pro',
    'products.subtitle': 'Professioneel inventaris- en productbeheersysteem FIFA',
    'products.category.equipment': 'Uitrusting',
    'products.category.maintenance': 'Onderhoud',
    'products.category.marking': 'Markering',
    'products.category.measurement': 'Meting',
    'products.category.certification': 'Certificering',
    'products.featured': 'Uitgelichte Producten',
    'products.new': 'Nieuwe Producten',
    'products.bestseller': 'Bestsellers',
    'products.on.sale': 'In de Aanbieding',
    'products.price': 'Prijs',
    'products.availability': 'Beschikbaarheid',
    'products.in.stock': 'Op Voorraad',
    'products.out.of.stock': 'Uitverkocht',
    'products.limited.stock': 'Beperkte Voorraad',
    'products.add.to.cart': 'Toevoegen aan Winkelwagen',
    'products.buy.now': 'Nu Kopen',
    'products.view.details': 'Details Bekijken',
    'products.specifications': 'Specificaties',
    'products.reviews': 'Beoordelingen',
    'products.rating': 'Waardering',
    'products.warranty': 'Garantie',
    'products.shipping': 'Verzending',
    'products.delivery': 'Levering',
    'products.compare': 'Vergelijken',
    'products.wishlist': 'Verlanglijst',
    'products.share': 'Delen',
    'products.similar': 'Vergelijkbare Producten',
    'products.accessories': 'Accessoires',
    'products.bundle': 'Bundel',
    'products.discount': 'Korting',
    'products.fifa.certified': 'FIFA Gecertificeerd',
    'products.uefa.approved': 'UEFA Goedgekeurd',
    'products.professional.grade': 'Professionele Kwaliteit',
    'products.search.placeholder': 'Zoek producten...',
    'products.filter.price': 'Filteren op Prijs',
    'products.filter.brand': 'Filteren op Merk',
    'products.filter.rating': 'Filteren op Waardering',
    'products.sort.name': 'Sorteren op Naam',
    'products.sort.price.asc': 'Prijs: Laag naar Hoog',
    'products.sort.price.desc': 'Prijs: Hoog naar Laag',
    'products.sort.rating': 'Sorteren op Waardering',
    'products.sort.newest': 'Nieuwste',
    'products.results': 'resultaten gevonden',
    'products.no.results': 'Geen producten gevonden',
    'products.clear.filters': 'Filters Wissen',
    'products.items': 'Producten',
    'products.low.stock': 'Lage Voorraad',
    'products.fifa.standards': 'FIFA Standaarden',
    'products.inventory.status': 'Voorraadstatus'
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.measurement': 'Measurement',
    'nav.marking': 'Marking',
    'nav.fields': 'Fields',
    'nav.history': 'History',
    'nav.export': 'Export',
    'nav.map': 'Map',
    'nav.calendar': 'Calendar',
    'nav.products': 'Products',
    
    // Home
    'home.title': 'Lissewege Fields - R.F.C. Lissewege',
    'home.subtitle': 'Intelligent system for field measurement and marking',
    'home.measurement': 'Measurement',
    'home.measurement.desc': 'Measure field dimensions',
    'home.marking': 'Marking',
    'home.marking.desc': 'Mark field lines',
    'home.fields': 'Fields',
    'home.fields.desc': 'Manage sports fields',
    'home.history': 'History',
    'home.history.desc': 'View previous measurements',
    'home.features': 'Features',
    'home.camera': 'Integrated camera for measurement',
    'home.gps': 'High precision GPS',
    'home.fifa': 'FIFA standards',
    'home.multiple': 'Multiple fields',
    
    // Camera tools
    'camera.tools': 'Camera Tools',
    'camera.tracking': 'Tracking Point',
    'camera.tracking.desc': 'Central point to follow while walking',
    'camera.guidelines': 'Guide Lines',
    'camera.guidelines.desc': 'Parallel lines to maintain straightness',
    'camera.measurement': 'Live Measurement',
    'camera.measurement.desc': 'Real-time measurement on screen',
    'camera.tracker': 'Path Tracker',
    'camera.tracker.desc': 'Visualize walked path',
    'camera.straightness': 'Straightness Checker',
    'camera.straightness.desc': 'Analyze if line is straight',
    'camera.width': 'Guide lines width',
    'camera.distance': 'Distance covered',
    'camera.rectitude': 'Straightness',
    
    // Measurement
    'measurement.title': 'Mobile Measurement',
    'measurement.start': 'Start Measurement',
    'measurement.stop': 'Stop Measurement',
    'measurement.camera.start': 'Activate Camera',
    'measurement.camera.stop': 'Deactivate Camera',
    'measurement.gps.start': 'Activate GPS',
    'measurement.gps.stop': 'Deactivate GPS',
    'measurement.capture': 'Capture Point',
    'measurement.clear': 'Clear',
    'measurement.points': 'points',
    'measurement.distance.estimated': 'Estimated distance',
    'measurement.advanced': 'Advanced Mode',
    'measurement.tap.capture': 'Tap to capture',
    'measurement.tap.start': 'Tap "Start" to begin measurement',
    'measurement.camera.inactive': 'Camera not active',
    'measurement.camera.activating': 'Activating camera...',
    'measurement.camera.active': 'Camera active. Tap screen to capture points.',
    'measurement.camera.error': 'Could not access camera. Check permissions.',
    'measurement.camera.error.init': 'Error starting camera.',
    'measurement.camera.stopped': 'Camera stopped.',
    'measurement.gps.getting': 'Getting GPS position...',
    'measurement.stopped': 'Measurement stopped. At least 2 points needed.',
    'measurement.reset': 'Measurement reset.',
    'measurement.web.penalty.north': 'North Penalty Area',
    'measurement.web.penalty.south': 'South Penalty Area',
    'measurement.web.center.circle': 'Center Circle',
    'measurement.web.type.line': 'Line',
    'measurement.web.camera.starting': 'Starting camera for measurement...',
    'measurement.web.camera.ready': 'Camera active. Tap screen to capture measurement points.',
    'measurement.web.camera.error': 'Could not access camera. Check permissions.',
    'measurement.web.gps.connecting': 'Connecting to high precision GPS for FIFA measurement...',
    'measurement.web.gps.active': 'High precision GPS active. Ready for professional FIFA measurement.',
    'measurement.web.gps.error': 'Error getting GPS position. Check location permissions.',
    'measurement.web.fifa.start': 'Professional FIFA measurement started. High precision GPS system active.',
    'measurement.web.fifa.stopped': 'Measurement stopped. Calculating FIFA results...',
    'measurement.web.tracking.active': 'Tracking mode active. Camera will automatically detect lines.',
    'measurement.web.mode.basic': 'Basic Mode',
    'measurement.web.mode.advanced': 'Advanced Mode',
    'measurement.web.activate.gps': 'Activate GPS',
    'measurement.web.start.pro': 'Start Pro Measurement',
    'measurement.web.activate.camera': 'Activate Camera',
    'measurement.web.stop.camera': 'Stop Camera',
    'measurement.length.total': 'Total Length',
    'measurement.width.total': 'Total Width',
    'measurement.distance.walked': 'Distance Walked',
    'measurement.recording': 'Recording...',
    'measurement.ready': 'Ready',
    
    // Advanced Mode
    'advanced.mode.on': 'Advanced Mode ON',
    'advanced.mode.off': 'Basic Mode',
    'advanced.configuration': 'Advanced Configuration',
    'advanced.features.enabled': 'Active Features',
    'advanced.more': 'more',
    'advanced.camera.ai': 'Camera AI',
    'advanced.camera.ai.desc': 'Intelligent detection with computer vision',
    'advanced.line.detection': 'Line Detection',
    'advanced.line.detection.desc': 'Automatic recognition of field lines',
    'advanced.precision.tracking': 'Precision Tracking',
    'advanced.precision.tracking.desc': 'Professional sub-metric GPS tracking',
    'advanced.analytics.realtime': 'Real-time Analytics',
    'advanced.analytics.realtime.desc': 'Instant metrics and statistics',
    'advanced.camera.tools': 'Camera Tools',
    'advanced.camera.tools.desc': 'Intelligent overlay and measurement guides',
    'advanced.gps.professional': 'Professional GPS',
    'advanced.gps.professional.desc': 'Advanced positioning configuration',
    'advanced.category.camera': 'Camera',
    'advanced.category.gps': 'GPS',
    'advanced.category.ai': 'Artificial Intelligence',
    'advanced.category.analytics': 'Analytics',
    
    // AI and Detection
    'ai.detection.active': 'AI Active',
    'ai.confidence': 'Confidence',
    'ai.lines.detected': 'Lines',
    'ai.legend': 'Legend',
    'ai.boundary.lines': 'Boundary Lines',
    'ai.goal.lines': 'Goal Lines',
    'ai.penalty.lines': 'Penalty Area',
    'ai.center.line': 'Center Line',
    
    // Marking
    'marking.title': 'Mobile Marking',
    'marking.line.center': 'Center Line',
    'marking.line.penalty': 'Penalty Area',
    'marking.line.corner': 'Corner Circle',
    'marking.line.goal': 'Goal Area',
    'marking.progress': 'Progress',
    'marking.complete': 'Complete Line',
    'marking.reset': 'Reset Marking',
    'marking.line.goal.north': 'North Goal Line',
    'marking.line.goal.south': 'South Goal Line',
    'marking.line.side.left': 'Left Side Line',
    'marking.line.side.right': 'Right Side Line',
    'marking.circle.center': 'Center Circle',
    'marking.camera.activating': 'Activating camera...',
    'marking.camera.active': 'Camera active. Tap screen to mark points.',
    'marking.camera.error': 'Could not access camera. Check permissions.',
    'marking.camera.error.init': 'Error starting camera.',
    'marking.camera.stopped': 'Camera stopped.',
    'marking.gps.getting': 'Getting GPS position...',
    'marking.gps.active': 'GPS active. Move device to mark lines.',
    
    // Settings
    'settings.language': 'Language',
    'settings.spanish': 'Spanish',
    'settings.dutch': 'Dutch',
    'settings.english': 'English',
    
    // Status
    'status.online': 'Online',
    'status.offline': 'Offline',
    'status.connecting': 'Connecting...',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.measuring': 'Measuring...',
    'status.marking': 'Marking...',
    'status.gps': 'GPS Active',
    
    // General buttons
    'btn.start': 'Start',
    'btn.stop': 'Stop',
    'btn.continue': 'Continue',
    'btn.complete': 'Complete',
    'btn.cancel': 'Cancel',
    'btn.save': 'Save',
    'btn.clear': 'Clear',
    'btn.reset': 'Reset',
    
    // Calendar
    'calendar.title': 'Event Calendar',
    'calendar.no.events': 'No events scheduled',
    'calendar.add.event': 'Add Event',
    'calendar.today': 'Today',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.event.maintenance': 'Field Maintenance',
    'calendar.event.match': 'Match',
    'calendar.event.training': 'Training',
    'calendar.event.inspection': 'Inspection',
    'calendar.event.tournament': 'Tournament',
    'calendar.event.meeting': 'Meeting',
    'calendar.event.details': 'Event Details',
    'calendar.event.start': 'Start',
    'calendar.event.end': 'End',
    'calendar.event.location': 'Location',
    'calendar.event.description': 'Description',
    'calendar.event.participants': 'Participants',
    'calendar.event.status': 'Status',
    'calendar.event.confirmed': 'Confirmed',
    'calendar.event.pending': 'Pending',
    'calendar.event.cancelled': 'Cancelled',
    'calendar.filter.all': 'All Events',
    'calendar.filter.maintenance': 'Maintenance',
    'calendar.filter.matches': 'Matches',
    'calendar.filter.training': 'Training',
    'calendar.upcoming': 'Upcoming Events',
    'calendar.past': 'Past Events',
    'calendar.reminder': 'Reminder',
    'calendar.notification': 'Notification',
    'calendar.sync': 'Synchronize',
    'calendar.export': 'Export Calendar',
    'calendar.import': 'Import Events',
    
    // Products
    'products.title': 'Product Management Pro',
    'products.subtitle': 'Professional inventory and FIFA product management system',
    'products.category.equipment': 'Equipment',
    'products.category.maintenance': 'Maintenance',
    'products.category.marking': 'Marking',
    'products.category.measurement': 'Measurement',
    'products.category.certification': 'Certification',
    'products.featured': 'Featured Products',
    'products.new': 'New Products',
    'products.bestseller': 'Bestsellers',
    'products.on.sale': 'On Sale',
    'products.price': 'Price',
    'products.availability': 'Availability',
    'products.in.stock': 'In Stock',
    'products.out.of.stock': 'Out of Stock',
    'products.limited.stock': 'Limited Stock',
    'products.add.to.cart': 'Add to Cart',
    'products.buy.now': 'Buy Now',
    'products.view.details': 'View Details',
    'products.specifications': 'Specifications',
    'products.reviews': 'Reviews',
    'products.rating': 'Rating',
    'products.warranty': 'Warranty',
    'products.shipping': 'Shipping',
    'products.delivery': 'Delivery',
    'products.compare': 'Compare',
    'products.wishlist': 'Wishlist',
    'products.share': 'Share',
    'products.similar': 'Similar Products',
    'products.accessories': 'Accessories',
    'products.bundle': 'Bundle',
    'products.discount': 'Discount',
    'products.fifa.certified': 'FIFA Certified',
    'products.uefa.approved': 'UEFA Approved',
    'products.professional.grade': 'Professional Grade',
    'products.search.placeholder': 'Search products...',
    'products.filter.price': 'Filter by Price',
    'products.filter.brand': 'Filter by Brand',
    'products.filter.rating': 'Filter by Rating',
    'products.sort.name': 'Sort by Name',
    'products.sort.price.asc': 'Price: Low to High',
    'products.sort.price.desc': 'Price: High to Low',
    'products.sort.rating': 'Sort by Rating',
    'products.sort.newest': 'Newest',
    'products.results': 'results found',
    'products.no.results': 'No products found',
    'products.clear.filters': 'Clear Filters',
    'products.items': 'Products',
    'products.low.stock': 'Low Stock',
    'products.fifa.standards': 'FIFA Standards',
    'products.inventory.status': 'Inventory Status'
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>('es')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('lissewege-language') as Language
    if (savedLanguage && ['es', 'nl', 'en'].includes(savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('lissewege-language', lang)
  }

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}